### ISSUE TITLE
Bug: Cert validation fails on Kubernetes clusters that were created before 1.17 with Python 3.13+

### ISSUE THREAD

**Issue by bengaywins** [kiwigrid/k8s-sidecar#400]
A closed issue due to being stale: #377 

[This](https://github.com/python/cpython/issues/135408) issue is being investigated, but as a result of a new release, 1.30.3 is fine but 1.30.5 is not. I only know this because Jenkins consumes this image and their latest update is broken for us. When we revert to a release using 1.30.3, all is fine. Not sure if 1.30.4 is impacted.

**Comment by kaisen-san** [comment]
Positive! I'm facing the same issue with a Jenkins instance that I just upgraded. Interestingly, I upgraded another instance yesterday to the same Jenkins version, and it doesn't have the issue. The issue (or the solution to it) might not be here, though. Please check https://github.com/kubernetes-client/python/issues/2415.

**Comment by bengaywins** [comment]
Yeah that seems to be the same bug.

**Comment by Janfy** [comment]
Same issue with Jenkins (chart version: jenkins-5.8.62, app version: 2.504.3) using version 1.30.4 or 1.30.5.
Works fine with 1.30.3.

**Comment by jim-barber-he** [comment]
I suspect I'm having the same issue, but in a different environment.

The Grafana Helm chart hosted at https://github.com/grafana/helm-charts.git uses `kiwigrid/k8s-sidecar` as a sidecar container to find ConfigMaps in a Kubernetes cluster with a specific label so that it can provision Grafana Dashboards from them.
Version `9.2.8` of this Helm chart bumped the version of `kiwigrid/k8s-sidecar` from version `1.30.0` to `1.30.5`.

After upgrading to the new Grafana Helm chart I noticed a bunch of dashboards were missing in Grafana.
Looking at the container logs I saw entries like so:
```
{"time": "2025-06-30T03:48:39.269709+00:00", "level": "WARNING", "msg": "Retrying (Retry(total=4, connect=10, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier (_ssl.c:1028)'))': /api/v1/configmaps?labelSelector=grafana_dashboard&timeoutSeconds=60&watch=True"}
{"time": "2025-06-30T03:48:34.257056+00:00", "level": "ERROR", "msg": "MaxRetryError when calling kubernetes: HTTPSConnectionPool(host='100.64.0.1', port=443): Max retries exceeded with url: /api/v1/configmaps?labelSelector=grafana_dashboard&timeoutSeconds=60&watch=True (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier (_ssl.c:1028)')))\n"}
```

I redeployed the container with the `SKIP_TLS_VERIFY` environment variable set to `true` to bypass the problem for now.

**Comment by ChristianGeie** [comment]
Hi, in v1.30.5 python kubernetes lib was updated, see #398. So, if i understand https://github.com/kubernetes-client/python/issues/2415 right, this can be the root cause.

**Comment by booleanbetrayal** [comment]
> After upgrading to the new Grafana Helm chart I noticed a bunch of dashboards were missing in Grafana. 

Also experienced this as well. Ringing the upstream PR.

**Comment by bengaywins** [comment]
@kaisen-san @Janfy a new chart with this update [reverted has arrived](https://github.com/jenkinsci/helm-charts/releases/tag/jenkins-5.8.65).

**Comment by ChristianGeie** [comment]
Thank you very much for your research and findings. Is it possible for you to test this with version v1.30.6?

**Comment by jim-barber-he** [comment]
I still have the same problem with this new version.
I made this change in my grafana deployment:
```diff
        enableServiceLinks: true
        containers:
          - name: grafana-sc-dashboard
-           image: "quay.io/kiwigrid/k8s-sidecar:1.30.5"
+           image: "quay.io/kiwigrid/k8s-sidecar:1.30.6"
            imagePullPolicy: IfNotPresent
            env:
              - name: METHOD
...
                value: "both"
              - name: NAMESPACE
                value: "ALL"
-             - name: SKIP_TLS_VERIFY
-               value: "true"
              - name: REQ_USERNAME
                valueFrom:
                  secretKeyRef:
```

And the logs on the container say
```
{"time": "2025-07-03T06:03:21.539591+00:00", "level": "ERROR", "msg": "MaxRetryError when calling kubernetes: HTTPSConnectionPool(host='100.64.0.1', port=443): Max retries exceeded with url: /api/v1/secrets?labelSelector=grafana_dashboard&timeoutSeconds=60&watch=True (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier (_ssl.c:1028)')))\n"}
```

**Comment by ChristianGeie** [comment]
@jim-barber-he thank you very much for your efforts and testing. i will downgrade the [python kubernetes](https://github.com/kubernetes-client/python/releases/tag/v32.0.1) lib to 32.0.1, as i suspect that this is where the problem lies and that it should therefore be fixed upstream.
That should also give me a little more time to test it myself.

**Comment by ChristianGeie** [comment]
My key findings regarding TLS certificate verification against the Kubernetes API

**TLS Certificate Verification with the Kubernetes API**

Default Behavior:
- When running inside a Kubernetes cluster, the Python Kubernetes client uses the ServiceAccount credentials and the CA certificate automatically mounted at `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` for secure communication with the API server

Certificate Verification:
- By default, certificate verification is enabled. The client will only trust the API server if its certificate is signed by the CA provided in the mounted file. This is a critical security feature to prevent man-in-the-middle attacks

Common Issues:
- If the API server's certificate is self-signed, missing required extensions (like Authority Key Identifier), or not signed by the expected CA, you may encounter errors such as:
`SSLCertVerificationError: certificate verify failed: Missing Authority Key Identifier`
or
`MaxRetryError: HTTPSConnectionPool(...): Max retries exceeded with url: ... (Caused by SSLError(...))`

Disabling Verification (Not Recommended for Production):
- You can disable certificate verification by setting the environment variable SKIP_TLS_VERIFY=true. This should only be used for testing or in trusted environments, as it makes the connection insecure

Best Practice:
For production, always ensure:

- The API server presents a valid certificate signed by the cluster CA
- The CA certificate in the pod matches the one used by the API server
- Do **not** disable certificate verification unless absolutely necessary

Debugging Tips:

- Check the certificate presented by the API server using `openssl s_client -connect <api-server>:443 -showcerts`.
- Compare it with the CA certificate in your pod
- If you encounter verification errors, review your cluster's certificate setup

Additional notes:

I could not find any errors in the code, which does not mean it is perfect.

**Comment by bengaywins** [comment]
The API server isn't something we have control over in EKS, GKE, AKS, etc. The entire control plane is not managed by us.

Also, I am not sure how to test this, but from the thread I commented on for cpython, can you try [this](https://github.com/python/cpython/issues/135408#issuecomment-3032829062) and see what happens?

**Comment by ChristianGeie** [comment]
@bengaywins Thanks for the clarification - you're absolutely right.

In managed Kubernetes environments like EKS, GKE, or AKS, we don’t have control over the API server certificates, and that makes it difficult to address certificate validation issues from the client side. Since the Python Kubernetes client now performs stricter certificate checks (as seen in [kubernetes-client/python#2415](https://github.com/kubernetes-client/python/issues/2415)), this leads to problems when the API server presents certs that are missing required extensions like `Authority Key Identifier`.

For now, I’ve decided to downgrade the `kubernetes` Python library to version `32.0.1` in our image to restore compatibility. This should give us some breathing room while the upstream issue is being discussed and (hopefully) fixed in a future release.

I’ll also add some clearer documentation around `SKIP_TLS_VERIFY` and the certificate expectations in general, to help others who might run into this.

Thanks again for your input and your efforts to track this down!

**Comment by ChristianGeie** [comment]
Hi @jim-barber-he,

Thanks again for your detailed testing and feedback - that really helped a lot!

I've just published version `1.30.7` of the `k8s-sidecar` image, which includes a downgrade of the `kubernetes` Python client back to version `32.0.1`.  
This should bypass the stricter certificate validation introduced in later versions and might resolve the TLS verification issue you've encountered.

If you have a chance, could you please try `quay.io/kiwigrid/k8s-sidecar:1.30.7` in your environment and let us know if the problem persists?

Really appreciate your help!

**Comment by bengaywins** [comment]
When my coworkers and I do our Jenkins upgrade on Thursday, we can see if we can test it then.

**Comment by ChristianGeie** [comment]
Thanks @bengaywins - that would be great!

Please let me know how it goes after your upgrade on Thursday. If it still fails, I’d be happy to dig deeper based on your findings.

**Comment by jim-barber-he** [comment]
Ok this time the diff is this (I no longer have SKIP_TLS_VERIFY since I went back to 1.30.3.
```diff
        enableServiceLinks: true
        containers:
          - name: grafana-sc-dashboard
-           image: "quay.io/kiwigrid/k8s-sidecar:1.30.3"
+           image: "quay.io/kiwigrid/k8s-sidecar:1.30.7"
            imagePullPolicy: IfNotPresent
            env:
              - name: METHOD
```
But I am still seeing the problem with this version:
```
{"time": "2025-07-09T06:45:41.402261+00:00", "level": "WARNING", "msg": "Retrying (Retry(total=0, connect=10, read=5, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier (_ssl.c:1028)'))': /api/v1/secrets?labelSelector=grafana_dashboard&timeoutSeconds=60&watch=True"}

{"time": "2025-07-09T06:45:41.404361+00:00", "level": "ERROR", "msg": "MaxRetryError when calling kubernetes: HTTPSConnectionPool(host='100.64.0.1', port=443): Max retries exceeded with url: /api/v1/configmaps?labelSelector=grafana_dashboard&timeoutSeconds=60&watch=True (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier (_ssl.c:1028)')))\n"}
```

**Comment by ChristianGeie** [comment]
Thanks a lot for testing it so quickly, @jim-barber-he.

It’s unfortunate that the issue still persists with `1.30.7`, even after downgrading the Kubernetes Python client. Based on the logs, it's still failing during certificate validation due to the missing `Authority Key Identifier`.

Just to confirm: Are you running in a managed Kubernetes environment (e.g. GKE, EKS, AKS)? In those cases, we don’t have any control over the API server certificate, and this seems to be the core issue.

For reference: I'm running this same sidecar version in a **Google Kubernetes Engine (GKE) cluster with version v1.31**, and I **haven’t seen this issue** there - which suggests that the problem may depend on the exact API server certificate chain used in each environment.

One thing worth testing: could you try adding back the `SKIP_TLS_VERIFY=true` environment variable **temporarily**, just to confirm whether the certificate is truly the root cause again?

Also, it would be helpful to inspect and compare the certificates involved:

1. Check the CA certificate mounted in the container:

   ```bash
   kubectl exec <sidecar-pod> -- cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | openssl x509 -text -noout

2. Check the certificate presented by the Kubernetes API server

   ```bash
   openssl s_client -connect kubernetes.default.svc:443 -showcerts

The CA `Issuer` must match to serviceaccounts `Subject` and `openssl` can help here:

   ```bash
   kubectl exec <sidecar-pod> -- cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt > ca.crt
   openssl s_client -connect kubernetes.default.svc:443 -showcerts </dev/null 2>/dev/null \
   | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' \
   > server.crt
   openssl verify -CAfile ca.crt server.crt
   ```
The expected output should be `server.crt: OK`. Based on the python client error message i expect something like 

   ```
   unable to get issuer certificate
   self signed certificate
   certificate verify failed: Missing Authority Key Identifier
   ```
Tip: If you're using the NGINX Ingress Controller, its Pod already contains `openssl`, so you can exec into it directly to run the same checks without creating a debug pod:

   ```bash
   kubectl exec -it <nginx-ingress-pod> -- openssl s_client -connect kubernetes.default.svc:443 -showcerts
   ```

Bonus: If your API server is publicly accessible (e.g. in some EKS/GKE setups), you can also run:

   ```bash
   openssl s_client -connect <api-server-public-ip>:443 -showcerts
   ```
   You can extract `api-server-public-ip` from your kube config (`~/.kube/config`) using
   ```bash
   kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'
   ```


This way, we can verify whether the mounted CA is actually able to validate the server certificate or if something is missing (e.g. Authority Key Identifier or issuer mismatch).

I’ll continue looking into additional options to improve compatibility. Thanks again for your support and time!

**Comment by jim-barber-he** [comment]
I'm running self-managed clusters created via kOps ( https://github.com/kubernetes/kops/tree/master )

Ok so I just ran myself a pod like so:
```
kubectl run --rm -it debian-$(date '+%F-%H-%M-%S') --namespace default --image=debian:stable --restart=Never -- bash
```
Then ran a `apt update; apt install openssl` in it.

Then I did this:
```
cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt .
```
```
openssl s_client -connect kubernetes.default.svc:443 -showcerts </dev/null 2>/dev/null | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' > server.crt
```
And it verifies fine
```
root@debian-2025-07-09-16-31-25:~# openssl verify -CAfile ca.crt server.crt
server.crt: OK
```

I also did:
```
$ kubectl exec -t -i deploy/grafana -c grafana-sc-dashboard -- cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
And compared it to the ca.crt from my own running pod and it's the same (as you'd expect).

Other things you wanted...
The ca.crt in text format.
```
$ kubectl exec -t -i deploy/grafana -c grafana-sc-dashboard -- cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | openssl x509 -noout -text

Certificate:
                Data:
                             Version: 3 (0x2)
                                                     Serial Number:
                                                                               15:59:bc:eb:39:0d:d4:1c:50:b8:65:ef
                                                                                                                          Signature Algorithm: sha256WithRSAEncryption
                                                                                                                                                                              Issuer: CN=kubernetes
                                                                                                                                                                                                           Validity
                                                                                                                                                                                                                               Not Before: Sep 30 08:21:06 2018 GMT
                                                          Not After : Sep 29 08:21:06 2028 GMT
                                                                                                      Subject: CN=kubernetes
                                                                                                                                    Subject Public Key Info:
                                                                                                                                                                        Public Key Algorithm: rsaEncryption
                                                                                                                                                                                                                           Public-Key: (2048 bit)
                Modulus:
                    00:c7:b4:5b:6e:94:c0:98:60:37:b6:75:61:a8:2d:
                    25:b0:65:d1:9a:49:61:f1:cb:76:38:8b:45:c2:27:
                    12:07:16:cc:c9:e7:58:a1:58:b2:e3:74:9c:eb:a5:
                    a4:48:a1:83:6a:47:8a:da:fa:78:84:8a:e4:58:4a:
                    38:b4:51:50:3a:e3:d8:92:80:e8:b8:ac:9a:b4:41:
                    c2:8f:6e:42:f5:cd:fc:80:8b:97:b9:c3:ee:41:37:
                    be:8f:f6:ff:85:6c:67:a3:53:f2:6d:bc:a8:15:d5:
                    43:7b:ff:fe:81:5e:67:04:cf:c0:be:18:21:12:a2:
                    28:38:30:d6:6a:c3:0d:d5:06:45:41:9d:98:5c:50:
                    1c:5c:c2:a0:a7:77:46:c5:30:8f:77:a5:9a:ed:e9:
                    60:28:24:88:d6:24:2c:e7:bd:40:64:c0:e8:31:95:
                    a4:8f:85:54:05:95:e0:12:d0:db:cd:5d:1e:35:18:
                    79:ce:81:c9:c9:54:2f:99:1e:c2:65:b4:8a:81:54:
                    b4:a5:79:ff:2e:61:56:2c:bb:13:40:97:3c:f3:cc:
                    2f:11:36:72:9d:cc:ab:52:b3:27:98:13:86:f6:06:
                    15:d2:2e:44:d5:34:9b:d7:c0:31:6f:64:b2:b5:31:
                    9c:46:8f:ab:1b:9a:aa:8d:76:fb:9d:a8:b6:b7:24:
                    5d:db
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        8e:22:a8:a3:21:69:18:f5:a8:5d:2f:1b:79:df:32:02:38:fe:
        bb:6a:7c:3a:08:95:c0:16:8c:6b:25:51:74:14:a0:9a:1b:58:
        95:22:e5:9a:76:d8:33:4b:3f:c6:b0:ef:71:b5:b0:5e:c0:6a:
        af:f0:11:12:2e:a4:67:ca:0b:24:a2:c9:1d:ab:a8:d7:91:07:
        da:fa:a4:64:03:1e:04:07:e5:0a:47:0f:fb:b0:9b:94:21:a3:
        51:74:10:18:6f:ea:bc:48:0b:9f:ab:43:25:67:a3:6a:6b:68:
        3e:f2:ac:d6:83:2f:de:6c:f1:d9:91:a4:ee:d2:d8:ce:08:0b:
        8a:87:82:33:20:50:29:e9:c1:47:09:c1:c4:0c:37:ae:95:d0:
        f4:04:c5:04:d5:38:f7:97:b2:7f:1b:85:31:8a:62:a8:3c:d9:
        b4:3c:d7:22:94:57:50:6a:a6:04:f1:95:42:e2:2d:54:26:c7:
        b8:1b:9c:4d:81:9d:31:18:ce:d6:53:7d:20:4b:0d:2a:4d:ef:
        3e:cc:64:23:4c:63:bd:64:2b:61:98:ec:73:8a:7d:04:88:05:
        73:1e:e0:ae:55:ed:c6:4e:33:7a:44:9f:39:8e:39:7c:51:39:
        0d:35:41:a3:7b:4b:94:af:c8:df:39:41:1b:0c:de:41:b4:7c:
        5f:ad:3d:bb
```

From within the pod I created connecting to the Kube API server.
```
root@debian-2025-07-09-16-31-25:~# openssl s_client -connect kubernetes.default.svc:443 -showcerts
CONNECTED(00000003)
depth=1 CN = kubernetes
verify error:num=19:self-signed certificate in certificate chain
verify return:1
depth=1 CN = kubernetes
verify return:1
depth=0 CN = kubernetes-master
verify return:1
---
Certificate chain
 0 s:CN = kubernetes-master
   i:CN = kubernetes
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jun 17 05:56:12 2025 GMT; NotAfter: Oct 10 23:56:12 2026 GMT
-----BEGIN CERTIFICATE-----
MIID7TCCAtWgAwIBAgIQJeGjYspTbKoj/xBScX4t/DANBgkqhkiG9w0BAQsFADAV
MRMwEQYDVQQDEwprdWJlcm5ldGVzMB4XDTI1MDYxNzA1NTYxMloXDTI2MTAxMDIz
NTYxMlowHDEaMBgGA1UEAxMRa3ViZXJuZXRlcy1tYXN0ZXIwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQCuAMwb+W8jJhGQoZorD3iJkbAPxIEKlIXZRJaM
EUZ8fyydwXaLU5rgRFPeYZ4mscr8OFdRz4Hk5RhhUcCUZZpjc+d0/pHgZZ+Z2KMj
W1xRLD8sfduffz74nomJMT4ryQgjwSbBmtkhmuAHX7HlBua+zLkE6N1Ie4kcPUY7
EbzgEz8QWD6EE+ais3DQcdEfRXzfKo7sZogsUgOXZFkg5NUGEjxCeKF6hydGMpWn
wgh/E4oQw9reG4JyIPGDTGpVmas3DQrB34mS89lbZq7n1nhwSS1+7/p26oOWfbVC
MAJlyHyKU/mmUBWV+I0oOOGe0z14MSSj5A45bW9Zno94/VSpAgMBAAGjggEwMIIB
LDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/
BAIwADCB9gYDVR0RBIHuMIHrggprdWJlcm5ldGVzghJrdWJlcm5ldGVzLmRlZmF1
bHSCFmt1YmVybmV0ZXMuZGVmYXVsdC5zdmOCJGt1YmVybmV0ZXMuZGVmYXVsdC5z
dmMuY2x1c3Rlci5sb2NhbIIQYXBpLnRlc3QxLmhlMC5pb4IZYXBpLmludGVybmFs
LnRlc3QxLmhlMC5pb4JSYXBpLXRlc3QxLWhlMC1pby03N21vYXYtMS04cjdtM2wt
NjIxMDk4ZTkyNjBhOWUyOC5lbGIuYXAtc291dGhlYXN0LTIuYW1hem9uYXdzLmNv
bYcEZEAAAYcEfwAAATANBgkqhkiG9w0BAQsFAAOCAQEAtdexfYSq/DGKsiBnyDCV
keEGx4MjGyRqOfKhohzICrd4JHuThLvqlw0KSDKm02MD+RN/xRAGH78zMtZir2Q6
OVqLHD9TCNqHw4nWeAezPPZ35XNtSvYQdQ2CGUx5K6CtcMHW9AptPBtJVDMKtukV
zZD0nnxLbyQZwHtMVGCnzuydzUGiYXBmm8wE6jRl4WsPdLHGMOFNW1kL7aE2FEuD
OrnsqWKEbupwgL5q+joxHsF/kihqltsk5JbNeo+rf0xQV68pNDFeK/YMIR4L+zG9
G4WwHCzbNBTu6g8FqpYhOksKfCqWijkxQzpmD4PILdVifhNqhv5tp5aDtSMtxftk
GA==
-----END CERTIFICATE-----
 1 s:CN = kubernetes
   i:CN = kubernetes
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep 30 08:21:06 2018 GMT; NotAfter: Sep 29 08:21:06 2028 GMT
-----BEGIN CERTIFICATE-----
MIIC0zCCAbugAwIBAgIMFVm86zkN1BxQuGXvMA0GCSqGSIb3DQEBCwUAMBUxEzAR
BgNVBAMTCmt1YmVybmV0ZXMwHhcNMTgwOTMwMDgyMTA2WhcNMjgwOTI5MDgyMTA2
WjAVMRMwEQYDVQQDEwprdWJlcm5ldGVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEAx7RbbpTAmGA3tnVhqC0lsGXRmklh8ct2OItFwicSBxbMyedYoViy
43Sc66WkSKGDakeK2vp4hIrkWEo4tFFQOuPYkoDouKyatEHCj25C9c38gIuXucPu
QTe+j/b/hWxno1PybbyoFdVDe//+gV5nBM/AvhghEqIoODDWasMN1QZFQZ2YXFAc
XMKgp3dGxTCPd6Wa7elgKCSI1iQs571AZMDoMZWkj4VUBZXgEtDbzV0eNRh5zoHJ
yVQvmR7CZbSKgVS0pXn/LmFWLLsTQJc888wvETZyncyrUrMnmBOG9gYV0i5E1TSb
18Axb2SytTGcRo+rG5qqjXb7nai2tyRd2wIDAQABoyMwITAOBgNVHQ8BAf8EBAMC
AQYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAjiKooyFpGPWo
XS8bed8yAjj+u2p8OgiVwBaMayVRdBSgmhtYlSLlmnbYM0s/xrDvcbWwXsBqr/AR
Ei6kZ8oLJKLJHauo15EH2vqkZAMeBAflCkcP+7CblCGjUXQQGG/qvEgLn6tDJWej
amtoPvKs1oMv3mzx2ZGk7tLYzggLioeCMyBQKenBRwnBxAw3rpXQ9ATFBNU495ey
fxuFMYpiqDzZtDzXIpRXUGqmBPGVQuItVCbHuBucTYGdMRjO1lN9IEsNKk3vPsxk
I0xjvWQrYZjsc4p9BIgFcx7grlXtxk4zekSfOY45fFE5DTVBo3tLlK/I3zlBGwze
QbR8X609uw==
-----END CERTIFICATE-----
---
Server certificate
subject=CN = kubernetes-master
issuer=CN = kubernetes
---
Acceptable client certificate CA names
CN = kubernetes
CN = apiserver-aggregator-ca
Requested Signature Algorithms: RSA-PSS+SHA256:ECDSA+SHA256:ed25519:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA384:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA-PSS+SHA256:ECDSA+SHA256:ed25519:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA384:ECDSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2417 bytes and written 422 bytes
Verification error: self-signed certificate in certificate chain
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 19 (self-signed certificate in certificate chain)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_128_GCM_SHA256
    Session-ID: 39E690CDDCE1D86BB12FE0F17263F85FF94554748A2F6F8507815B6D6DEB18CC
    Session-ID-ctx: 
    Resumption PSK: 55D9CFA6DB9767BF618CF10C236B11454BF005CFAE8E0C32E97947B572996EFD
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 604800 (seconds)
    TLS session ticket:
    0000 - 47 4a 96 2e 01 c2 40 7f-91 d5 8a 0d 6e d4 94 2f   GJ....@.....n../
    0010 - 78 a3 22 54 f5 12 01 90-96 8c eb 91 07 54 89 22   x."T.........T."
    0020 - 52 0d b2 ab a4 60 ce 75-96 fc 59 21 9e 0d 88 9b   R....`.u..Y!....
    0030 - c5 04 51 1e 36 9e e2 a7-41 30 65 a1 46 c2 be ab   ..Q.6...A0e.F...
    0040 - dc d4 cf 5b 72 ff f9 b7-78 26 70 bb fe 08 02 4b   ...[r...x&p....K
    0050 - 0d fb 20 87 13 d5 2a 58-5f ec cd 8d 57 45 91 84   .. ...*X_...WE..
    0060 - 63 d4 93 ab 04 0f 53 9e-eb                        c.....S..

    Start Time: 1752050710
    Timeout   : 7200 (sec)
    Verify return code: 19 (self-signed certificate in certificate chain)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
DONE
```

Finally here's the deploy with SKIP_TLS_VERIFY
```diff
        enableServiceLinks: true
        containers:
          - name: grafana-sc-dashboard
-           image: "quay.io/kiwigrid/k8s-sidecar:1.30.3"
+           image: "quay.io/kiwigrid/k8s-sidecar:1.30.7"
            imagePullPolicy: IfNotPresent
            env:
              - name: METHOD
...
                value: "both"
              - name: NAMESPACE
                value: "ALL"
+             - name: SKIP_TLS_VERIFY
+               value: "true"
              - name: REQ_USERNAME
                valueFrom:
                  secretKeyRef:
```
This works fine instead of errors it provisions my dashboards.
There were some warnings about having disabled verification which is expected
```
/app/.venv/lib/python3.13/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '100.64.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
```

**Comment by jim-barber-he** [comment]
I guess other info is that I'm running a `v1.32.6` cluster above.

My API server isn't publicly exposed, but I have a VPN into the AWS account so I can read it via the internal ALB it created.
The connection to it via `openssl s_client` looks more or less the same as when I accessed it from a pod (the exact same certificates were presented when I did a few runs). The `kubernetes` one is always the same, and the `kubernetes-master` one varied depending on which of my 3x control-plane servers answered.

**Comment by ChristianGeie** [comment]
Thanks a lot for the thorough analysis and for documenting all those steps, @jim-barber-he - this is super helpful!

It’s great to know that the CA and server certificate do verify cleanly with `openssl verify`, and that the connection works as expected when `SKIP_TLS_VERIFY=true` is set.  
Your finding confirms that the stricter validation introduced in recent OpenSSL and Python versions is what causes the issue - especially when self-signed certs are used, and the full trust chain isn’t fully compliant with modern expectations (e.g. full AKI/SKI matching, intermediate chains, etc.).

The variation between the `kubernetes-master` certificates depending on which control plane server answers is also an important insight. In managed environments this is usually abstracted away, but in self-managed clusters like kOps, these differences might surface more easily.

I'll look into options for improving the default behavior in such setups - possibly by adding support for a `TRUSTED_CA_FILE` override, or documenting more clearly when and why `SKIP_TLS_VERIFY` is required.

Thanks again for your help and precise debugging!

**Comment by ibakshay** [comment]
I also ran into this issue. I'm not sure if this information will be helpful for debugging, but I've deployed my application with `k8s-sidecar` to a fleet of clusters, and I'm only seeing the issue in the clusters with `linkerd`.

**Comment by bengaywins** [comment]
This is still an issue unfortunately, but not sure what to bother doing.

**Comment by bengaywins** [comment]
We updated to k8s 1.32 and still having this issue.

**Comment by HaveFun83** [comment]
We facing the same issue with version 1.30.10  on k8s v1.33.3

**Comment by gbenbow** [comment]
I'm seeing this issue in 2.1.2

**Comment by okhowang** [comment]
there is a workaround from https://github.com/kubernetes-client/python/issues/2394

**Comment by bengaywins** [comment]
I am going to open a ticket with AWS and see if it's possible for them to upgrade the CA certs. This is a real problem. Thank you @okhowang!

**Comment by bengaywins** [comment]
I have updated the title and being that this is _really_ a validation issue with kubernetes certificates and Python, I don't think it's valid to keep it open.
